### PR TITLE
Travis: use JRuby 9.1.7.0

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR moves the build matrix from building on JRuby on some version of jruby-1.7 to latest stable JRuby.

Using build number from https://github.com/rbenv/ruby-build/tree/master/share/ruby-build

### CODE REVIEW

**Comment by olleolleolle** [comment]
@tobmatth Would it be good to add 2.4.0 and bump to 2.3.3 and so forth?

**Comment by tobmatth** [comment]
Sure, keep going 👍🏻

**Comment by olleolleolle** [comment]
@tobmatth There!

**Comment by tobmatth** [comment]
Merged, thanks again!

**Pull request merged**
